services:
  mysql:
    image: mysql:8.0
    container_name: dawanow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dawanow
      MYSQL_USER: dawanow
      MYSQL_PASSWORD: dawanow
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
